In [1]:
lambda_=lambda argument1,argument2:argument1+argument2;
print("Value of the function is:",lambda_(10,5))
print("Value of the function is:",lambda_(15,20))


Value of the function is: 15
Value of the function is: 35


In [2]:
lambda_=lambda argument1,argument2:argument1*argument2;
print("Value of the function is:",lambda_(10,5))
print("Value of the function is:",lambda_(15,20))


Value of the function is: 50
Value of the function is: 300


In [4]:
import numpy as np
from time import process_time
python_list=[i for i in range(10000)]
start_time=process_time()
python_list=[i+5 for i in python_list]
end_time=process_time()
print(end_time-start_time)

0.0


In [7]:
np_array=np.array([i for i in range(10000)])
start_time=process_time()
np_array +=5
end_time=process_time()
print(end_time-start_time)

0.0


In [9]:
print(type(np_array))

<class 'numpy.ndarray'>


In [10]:
a=np.array([1,2,3,4])
print(a)
a.shape

[1 2 3 4]


(4,)

In [13]:
b=np.array([(1,2,3,4),(5,6,7,8)])
print(b)
print(b.shape)
c=np.array(b,dtype=float)
print(c)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


In [14]:
x=np.zeros((4,5))
print(x)
y=np.ones((3,3))
print(y)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [21]:
z=np.full((4,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [22]:
a=np.eye(5)
print(a)
b=np.random.random((3,4))
print(b)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[0.43559122 0.2664722  0.50341533 0.69312765]
 [0.50831003 0.21408671 0.76655154 0.00665011]
 [0.93013378 0.81209322 0.3193697  0.45232938]]
