In [3]:
import numpy as np
list_=[10,20,30,40]
np_array=np.asarray(list_)
print(np_array)
type(np_array)

[10 20 30 40]


numpy.ndarray

In [9]:
a=np.random.randint(0,10,(3,3))
b=np.random.randint(5,10,(3,3))
print(a)
print(b)
print(a*b)


[[9 9 9]
 [3 2 9]
 [9 0 1]]
[[5 7 9]
 [6 6 6]
 [9 7 9]]
[[45 63 81]
 [18 12 54]
 [81  0  9]]


In [10]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[14 16 18]
 [ 9  8 15]
 [18  7 10]]
[[ 4  2  0]
 [-3 -4  3]
 [ 0 -7 -8]]
[[45 63 81]
 [18 12 54]
 [81  0  9]]
[[1.8        1.28571429 1.        ]
 [0.5        0.33333333 1.5       ]
 [1.         0.         0.11111111]]


In [13]:
a=np.random.randint(5,10,(2,3))
b=a.reshape(3,2)
print(b)
print(b.shape)

[[6 6]
 [5 9]
 [5 7]]
(3, 2)
